# Generated by Django 3.1.7 on 2021-03-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned',
            name='Category_Name',
            field=models.ForeignKey(db_column='Category_Name', on_delete=django.db.models.deletion.CASCADE, to='reporting.category'),
        ),
        migrations.AlterField(
            model_name='assigned',
            name='PID',
            field=models.ForeignKey(db_column='PID', on_delete=django.db.models.deletion.CASCADE, to='reporting.product'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='Date',
            field=models.ForeignKey(db_column='Date', on_delete=django.db.models.deletion.CASCADE, to='reporting.day'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='PID',
            field=models.ForeignKey(db_column='PID', on_delete=django.db.models.deletion.CASCADE, to='reporting.product'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='Date',
            field=models.ForeignKey(db_column='Date', on_delete=django.db.models.deletion.CASCADE, to='reporting.day'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='Description',
            field=models.ForeignKey(db_column='Description', on_delete=django.db.models.deletion.CASCADE, to='reporting.advertisin_gcampaign'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='Date',
            field=models.ForeignKey(db_column='Date', on_delete=django.db.models.deletion.CASCADE, to='reporting.day'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Date',
            field=models.ForeignKey(db_column='Date', on_delete=django.db.models.deletion.CASCADE, to='reporting.day'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='PID',
            field=models.ForeignKey(db_column='PID', on_delete=django.db.models.deletion.CASCADE, to='reporting.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='Store_Number',
            field=models.ForeignKey(db_column='Store_Number', on_delete=django.db.models.deletion.CASCADE, to='reporting.store'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='PID',
            field=models.ForeignKey(db_column='PID', on_delete=django.db.models.deletion.CASCADE, to='reporting.product'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='Store_Number',
            field=models.ForeignKey(db_column='Store_Number', on_delete=django.db.models.deletion.CASCADE, to='reporting.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='City_Name',
            field=models.ForeignKey(db_column='City_Name', on_delete=django.db.models.deletion.RESTRICT, related_name='fk_STORE_CityName_CITY_CityName', to='reporting.city'),
        ),
        migrations.AlterField(
            model_name='store',
            name='State_Location',
            field=models.ForeignKey(db_column='State_Location', on_delete=django.db.models.deletion.RESTRICT, related_name='fk_STORE_StateLocation_CITY_StateLocation', to='reporting.city'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Time_Limit',
            field=models.ForeignKey(db_column='Time_Limit', on_delete=django.db.models.deletion.RESTRICT, to='reporting.childcare'),
        ),
    ]
